### ISSUE TITLE
How do you will handle the bower shutdown?

### ISSUE THREAD

**Issue by equinusocio** [PredixDev/px-dropdown#56]
Just a question, how do you will handle the bower shutdown and migration? Are you considering switching to npm?

**Comment by randyaskin** [comment]
I think "shutdown" is a strong word, from what I've read, bower is still going to be around, they're just not planning any more major improvements to it. As for migrating, the only version of Polymer on npm right now is v2, whereas all of our components currently use v1.9, so we won't be able to migrate to npm until we also migrate to Polymer 2 (which we're currently planning for). I know the Polymer team was also hesitant about npm at first due to its nested vs flat structure (somewhat resolved in v3) and lack of conflict resolution - Rob Dodson talked about that [here](https://youtu.be/D7ZSMw_qm8Q?t=3m10s).

**Comment by equinusocio** [comment]
And what about components dependencies that are on bower? Like every polymer components (iron, etc). 

Bower site tell to use another tool like webpack.. i think there is no future for him.

**Comment by randyaskin** [comment]
While we have regular communication with the Polymer team, I can't speak to their strategy on this, you'd have to ask them.

**Comment by equinusocio** [comment]
So, you are dependent on what the polymer team decides.

**Comment by mdwragg** [comment]
We use Polymer and Polymer components so we certainly are dependent on what they decide.
